//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Reflection.AssemblyInformationalVersion("1.0.47.59239 (git 3c3c47af8925affead4139c6759f4d667cdd49b2)")]
[assembly: System.Reflection.AssemblyVersion("1.0.47.59239")]
[assembly: System.Reflection.AssemblyFileVersion("1.0.47.59239")]


